### ISSUE TITLE
Application hangs if channel log buffer is full

### ISSUE THREAD

**Issue by mkobaly** [samber/slog-channel#1]
Since logging should not impact the application does it make sense to make the channel logger non blocking so that it will allow the application to continue to function as calls to slog will hang if the channel is full.

Should the Handle function be updated to something like

func (h *ChannelHandler) Handle(ctx context.Context, record slog.Record) error {
	fromContext := slogcommon.ContextExtractor(ctx, h.option.AttrFromContext)
	output := h.option.Converter(h.option.AddSource, h.option.ReplaceAttr, append(h.attrs, fromContext...), h.groups, &record)
select {
    case h.option.Channel <- output:
    default:
         //do nothing
    }
    return nil
}

**Comment by samber** [comment]
+1

Please upgrade to 1.2.0
